# Generated by Django 5.0.1 on 2024-02-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authour_name', models.CharField(blank=True, max_length=100, null=True)),
                ('blog_heading', models.CharField(blank=True, max_length=100, null=True)),
                ('blog_discreption', models.CharField(blank=True, max_length=100, null=True)),
                ('uploded_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('donaor', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiary', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('trancaction_method', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=100, null=True)),
                ('event_id', models.IntegerField()),
                ('event_address', models.CharField(blank=True, max_length=100, null=True)),
                ('event_city', models.CharField(blank=True, max_length=100, null=True)),
                ('event_state', models.CharField(blank=True, max_length=100, null=True)),
                ('event_host', models.CharField(blank=True, max_length=100, null=True)),
                ('event_date', models.DateField()),
            ],
        ),
    ]
