# Generated by Django 5.0.1 on 2024-02-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_user', '0002_blog_donation_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='authour_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_discreption',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_heading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customcharityuser',
            name='charity_address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customcharityuser',
            name='charity_city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customcharityuser',
            name='charity_id',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customcharityuser',
            name='charity_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customcharityuser',
            name='charity_state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='customcharityuser',
            name='charity_zipcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='beneficiary',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donaor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donation',
            name='trancaction_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_host',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_state',
            field=models.CharField(max_length=100),
        ),
    ]
