# Generated by Django 5.0.1 on 2024-02-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customuser_address_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('complint_name', models.CharField(blank=True, max_length=100, null=True)),
                ('crime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.IntegerField()),
                ('crime_date', models.DateField()),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
